version: "3.3"
services:
  plex-music-grabber:
    image: rutgernijhuis/plex-music-grabber
    build: .
    container_name: plex-music-grabber
    volumes:
      - ./library/Anime:/library/Anime
      - ./library/Shows:/library/Shows
      - ./library/Movies:/library/Movies
    environment:
      - interval=10
      - library_path=/library/Anime,/library/Shows,/library/Movies
    restart: unless-stopped
    network_mode: default
