version: "3.3"
services:
  plex-music-grabber:
    image: rutgernijhuis/plex-music-grabber
    build: .
    container_name: plex-music-grabber
    volumes:
      - ./library:/library
    environment:
      - interval=10
    restart: unless-stopped
    network_mode: default
