version: "3.3"
services:
  plex-music-grabber:
    image: rutgernijhuis/plex-music-grabber
    container_name: plex-music-grabber
    volumes:
      - ./demo-library:/library
    environment:
      - interval=60
    restart: unless-stopped
    network_mode: default
