name: build
run-name: Build new version
on:
# Run on master branch
  push:
    branches:
      - master
  schedule:
  # Run every sunday at 08:00
    - cron: '0 8 * * 0'
jobs:
  # https://github.com/marketplace/actions/build-and-push-docker-images
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Create tag
        id: tag
        run: echo ::set-output name=tag::$(date +'%Y.%m.%d')
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: rutgernijhuis/plex-music-grabber:latest,rutgernijhuis/plex-music-grabber:${{ steps.tag.outputs.tag }}