name: build
run-name: Build new version
on: [push]
jobs:
  # https://github.com/marketplace/actions/build-and-push-docker-images
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      #  Create tag based on date
      - name: Create tag
        id: tag
        # switch to new syntax
        run: echo "TAG = $(date +'%Y.%m.%d')" >> $GITHUB_ENV

      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: rutgernijhuis/plex-music-grabber:latest,rutgernijhuis/plex-music-grabber:$TAG"